# Generated by Django 5.0.7 on 2024-07-31 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='videos/')),
                ('filename', models.CharField(max_length=255, null=True)),
                ('processing', models.BooleanField(default=False)),
                ('processing_success', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
